version: '3.1'
services:
  app:
    container_name: person-ms
    image: durpyshark/person-ms
    build: ./
    ports:
      - "8084:8084"
    depends_on:
      - persons_db_container
  persons_db_container:
    image: postgres
    ports:
      - "5436:5436"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=persons_db
    command: -p 5436